### ISSUE TITLE
ajaxenabled() Error

### ISSUE THREAD

**Issue by oskeitje** [bobopinna/moodle-mod_reservation#1]
I've attempted to use this with my 2.9 Server but I receive the following error: 

"Coding error detected, it must be fixed by a programmer: ajaxenabled() can not be used anymore. Update your code to work with JS at all times." 

I'm not entirely aware of how to fix this problem.

**Comment by bobopinna** [comment]
I think you use a old release.
Current release didn't ajaxenabled anymore.
Please upgrade to the latest version.

**Comment by oskeitje** [comment]
I am using the most recent plugin version available on the Moodle plugins.

[image: Inline image 1]

If there is a newer version to install can you please tell me where to find
it?

**Comment by scan5415** [comment]
I have still this issue.
Fresh installation from the plugin repo...

Please reopen this issue.
