### ISSUE TITLE
Misleading or incorrect display of "available seats"

### ISSUE THREAD

**Issue by roessling** [bobopinna/moodle-mod_reservation#10]
Colleagues have set up a reservation with three slots. Two students have made a reservation.
When I view this as a teacher, I see "Requests 2/3, Available seats: 1".
When I switch to the student role, I - as well as all students - see "Available seats: 3", although only one seat is still available, and I would expect the display to be "Available seats: 1" (or perhaps "Available seats: 1/3").
I have looked through the code, but could not pinpoint the reason why the numbers are different...?

**Comment by bobopinna** [comment]
That's very strange.
I've tried to replicate your problem but went I switch to student role I see "Available seats: 1".
Did you use the last module release?
