### ISSUE TITLE
A space...

### ISSUE THREAD

**Issue by dinism** [bobopinna/moodle-mod_reservation#11]
![imagem](https://user-images.githubusercontent.com/14828021/41409280-8967d0b2-6fcd-11e8-8639-62d47cfdb4f2.png)

**Comment by bobopinna** [comment]
Duplicated of #9.

I checked the source code, all these space are present in source code till moodle 2.7 module release.
https://github.com/bobopinna/moodle-mod_reservation/blob/MOODLE_27_STABLE/view.php

Please check your theme and CSS.
