### ISSUE TITLE
Use of uninitialized value

### ISSUE THREAD

**Issue by ghost** [bobopinna/moodle-mod_reservation#13]
In version 3.5 (2018100600), line 236 of mod/reservation/lib.php is "echo 'Could not find teacher '.$request->teacher."\n";".  SonarQube shows a "use of uninitialized value" bug for this line and the remainder of the function uses $userrequest->teacher.

**Comment by bobopinna** [comment]
Fixed on github by commit d4f1f280aa3afe301e04c2720f4c286a0311df27 on September 2018.
