### ISSUE TITLE
Fatal error when no standard value for max_overbook given (moodle 3.8.2+)

### ISSUE THREAD

**Issue by mputzi** [bobopinna/moodle-mod_reservation#18]
The moodle-site (moodle 3.8.2+) _stalls_ when a new reservation activity is created.
Error message with debugging on:
Warning: A non-numeric value encountered in …/httpdocs/moodle/mod/reservation/mod_form.php on line 185
The error disappears as soon as all entries in the plugin configuration are made.

**Comment by bobopinna** [comment]
I can't get the same warning.
Did you use the last git commit?
