### ISSUE TITLE
Activity completion

### ISSUE THREAD

**Issue by ptramonti** [bobopinna/moodle-mod_reservation#19]
Hi Bobo,
when I set "Student must reserve to complete this activity" in the Activity completion, it works only if the student do the reserve and don't works if it's the teacher who reserve the student.
Our typical use is to show a Quiz only if the student has booked, and we would like the teacher to book some students (maybe with reservations already closed). But we have seen that if the teacher does it, the activity is not checked for the student!
It's possible to trigger completion even if the teacher does it?
Ciao
Paolo

**Comment by bobopinna** [comment]
Hi Paolo,
I restart to work on plugin in this days so I fixed it today.

Thanks a lot.

Ciao,
Roberto
