### ISSUE TITLE
Unsupported $module syntax detected in version.php of the mod_reservation plugin.

### ISSUE THREAD

**Issue by nitro2010-zz** [bobopinna/moodle-mod_reservation#2]
Hello,

Please update your plugin for Moodle v3.0

While installating I get errors [all text with debugging option on]:

Unsupported $module syntax detected in version.php of the mod_reservation plugin.
line 322 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin mod_reservation does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()

**Comment by fluxcorenz** [comment]
Certainly adding the $plugin->component fixes this (as in commit bf22af1), perhaps the maintainer needs to bump the version number to get people to upgrade the plugin before upgrading to moodle 3.0 though?

**Comment by bobopinna** [comment]
I will test all things before releasing a new version. That fix was just to go on.

**Comment by nitro2010-zz** [comment]
ok, thanks, it working
