### ISSUE TITLE
Error with cron

### ISSUE THREAD

**Issue by ptramonti** [bobopinna/moodle-mod_reservation#20]
Hi Bobo,
I discovered an issue with the latest version of your plugin (August 19, 2020): the cron job does not run!
I get the error:

```
Execute scheduled task: Send reservation and request grading mails (mod_reservation\task\cron_task)
... started 17:33:36. Current memory use 4.4MB.
!!! Eccezione - Call to undefined function mod_reservation\task\reservation_get_unmailed_requests() !!!
```

Could it be because I'm still using Moodle version 3.6.9?
Ciao
Paolo

**Comment by bobopinna** [comment]
Hi Paolo,
there was a bug.
Now I fixed it, please update and let my know.

Ciao,
Roberto

**Comment by ptramonti** [comment]
I can confirm you that the cron now is working correctly!
Thank you!
Paolo
