### ISSUE TITLE
mod_reservation breaks cron on moodle 3.9 with php 7.4

### ISSUE THREAD

**Issue by valmarku** [bobopinna/moodle-mod_reservation#21]
Sep 04 12:01:14 ttumoodle php[3157496]: Server Time: Fri, 04 Sep 2020 12:01:14 +0300
Sep 04 12:01:14 ttumoodle php[3157496]: Execute scheduled task: Send reservation and request grading mails (mod_reservation\task\cron_task)
Sep 04 12:01:14 ttumoodle php[3157496]: ... started 12:01:14. Current memory use 4.3MB.
Sep 04 12:01:14 ttumoodle php[3157496]: Default exception handler: Erand: Call to undefined function mod_reservation\task\reservation_get_unmailed_requests() Debug:
Sep 04 12:01:14 ttumoodle php[3157496]: Error code: generalexceptionmessage
Sep 04 12:01:14 ttumoodle php[3157496]: * line 64 of /mod/reservation/classes/task/cron_task.php: Error thrown
Sep 04 12:01:14 ttumoodle php[3157496]: * line 248 of /lib/cronlib.php: call to mod_reservation\task\cron_task->execute()
Sep 04 12:01:14 ttumoodle php[3157496]: * line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
Sep 04 12:01:14 ttumoodle php[3157496]: * line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
Sep 04 12:01:14 ttumoodle php[3157496]: * line 79 of /admin/cli/cron.php: call to cron_run()
Sep 04 12:01:14 ttumoodle php[3157496]: !!! Erand: Call to undefined function mod_reservation\task\reservation_get_unmailed_requests() !!!
Sep 04 12:01:14 ttumoodle php[3157496]: PHP Fatal error:  Uncaught Error: Call to a member function real_escape_string() on null in /srv/moodle/public_html/lib/dml/mysqli_native_moodle_database.php:1140
Sep 04 12:01:14 ttumoodle php[3157496]: Stack trace:
Sep 04 12:01:14 ttumoodle php[3157496]: #0 /srv/moodle/public_html/lib/dml/mysqli_native_moodle_database.php(1269): mysqli_native_moodle_database->emulate_bound_params()
Sep 04 12:01:14 ttumoodle php[3157496]: #1 /srv/moodle/public_html/lib/dml/moodle_database.php(1624): mysqli_native_moodle_database->get_records_sql()
Sep 04 12:01:14 ttumoodle php[3157496]: #2 /srv/moodle/public_html/lib/classes/lock/mysql_lock_factory.php(158): moodle_database->get_record_sql()
Sep 04 12:01:14 ttumoodle php[3157496]: #3 /srv/moodle/public_html/lib/classes/lock/lock.php(102): core\lock\mysql_lock_factory->release_lock()
Sep 04 12:01:14 ttumoodle php[3157496]: #4 /srv/moodle/public_html/lib/classes/lock/lock.php(116): core\lock\lock->release()
Sep 04 12:01:14 ttumoodle php[3157496]: #5 [internal function]: core\lock\lock->__destruct()
Sep 04 12:01:14 ttumoodle php[3157496]: #6 {main}
Sep 04 12:01:14 ttumoodle php[3157496]:   thrown in /srv/moodle/public_html/lib/dml/mysqli_native_moodle_database.php on line 1140
Sep 04 12:01:14 ttumoodle systemd[1]: moodlecron.service: Main process exited, code=exited, status=1/FAILURE

**Comment by bobopinna** [comment]
Hello,
I fixed it yesterday (#20).

Please pull the last release.
