### ISSUE TITLE
Deletion of reservation not working 

### ISSUE THREAD

**Issue by awludo** [bobopinna/moodle-mod_reservation#22]
Hi Bobo, in moodle 3.9.1 deletion of your reservation doesn't work. When selecting delete from dropdown, it does nothing.
plugin version: 2019031908

Thanks!

Ludovico

**Comment by bobopinna** [comment]
Hi Ludovico,
that was already fixed.
Please update to the last release from GitHub.

**Comment by cauca008** [comment]
HI Roberto,

have Moodle version 3.9.1+ (Build: 20200730). The plugin version I have is 2019031908. Looking at the above tread, cannot find on GitHub the latest version (am new to GitHub). 

Also, will it work with the latest version?

**Comment by bobopinna** [comment]
You can download the latest release from https://github.com/bobopinna/moodle-mod_reservation/archive/master.zip 
Unzip it and rename the folder to reservation.

I also released il on moodle.org
