### ISSUE TITLE
Handle username

### ISSUE THREAD

**Issue by unibasdev** [bobopinna/moodle-mod_reservation#23]
Dear devs,
thanks for the plugin, that we are using quite extensively.
We were wondering if there is the chance to add also "username" in the field that are shown and exported (perhaps adding a checkbox in the admin area, like other fields).
This is very useful in our context, since we using username as the "student id"

Thanks in advance

**Comment by bobopinna** [comment]
Usernames are normally not shown in Moodle interface to teachers and other users.
I added this choice in the last commit but administrators must evaluate if it's safe to expose them.

HTH
