### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by unibasdev** [bobopinna/moodle-mod_reservation#24]
Hello,
we are using your great module, and we noticed that the using the official mobile app we got an exception while opening a reservation:

Missing method in \mod_reservation\output\mobile

Do you have any plan to support mobile version?

Thanks

**Comment by bobopinna** [comment]
Hello,
please update to latest version to fix the exception.

I will work on mobile version in next months. 
I'm sorry but I don't have idea about release date.
