### ISSUE TITLE
Cron error (course_delete_modules & lock)

### ISSUE THREAD

**Issue by ghost** [bobopinna/moodle-mod_reservation#25]
I found an error in cron log...

![screen](https://user-images.githubusercontent.com/10725854/98095300-ace5e600-1e8a-11eb-846e-2077c799de8c.png)

The cause was determined using the following command:
`php admin/cli/adhoc_task.php --showsql --showdebugging --execute`

**I found out that in one table of the database (within the Reservation plugin) there is a record for a user that no longer exists.
The reservation request persisted in the given reservation from this user (table reservation_request).**

More info:
[https://moodle.org/mod/forum/discuss.php?d=413095]

**Comment by bobopinna** [comment]
I think I found a fix for it.

Please download last commit on github to get it.
