### ISSUE TITLE
Problem with translation on reserve and cancel button

### ISSUE THREAD

**Issue by parsa25eng** [bobopinna/moodle-mod_reservation#27]
Hi,
After translation customization for the "reserve" and "cancel reservation" buttons, these buttons not working.
I think that these clauses are hardcoded.
moodle version: 3.9
plugging version:mod_reservation_moodle39_2020081901
thank you,

**Comment by bobopinna** [comment]
Hi,
what do you mean with "buttons not working".
Translations are not hardcoded but managed with moodle get_string function.
Did you purge your language cache after customization?
