### ISSUE TITLE
Redirect issue

### ISSUE THREAD

**Issue by unibasdev** [bobopinna/moodle-mod_reservation#28]
Hi,
in our setup (docker installation behind apache) reservation redirects seems to be broken. 
In particular, when an user submit a reservation, the server generates a wrong redirect to
https://view.php/?id=6533

instead, of course, of something like https://<server>/moodle/course/view.php?id=6533

we fixed this by replacing `redirect ('view.php` with `redirect ('/moodle/mod/reservation/view.php`

It is a problem with some moodle configuration?

Thanks

**Comment by bobopinna** [comment]
Hi,
yes it could be a problem with any configuration that use a different directory name for moodle root directory.

I fix it in the common way `redirect ($CFG->wwwroot.'/mod/reservation/view.php` on commit 936983c

HTH
