### ISSUE TITLE
Problem after upgrading from 3.8 to 3.9

### ISSUE THREAD

**Issue by plrunner** [bobopinna/moodle-mod_reservation#29]
Hi,
a few days ago we upgraded Moodle from 3.8 to the latest 3.9.x. We were using php-fpm 7.2 in Moodle 3.8 and decided to stick with it, as still supported by Moodle 3.9. Apache is v2.4 on Ubuntu 18.04.

Sinche the upgrade we started experiecing a weird behaviour on a specific course page. Such page has only one particularity: it contains a pretty long list of reservations (a few hundred).

When loading that course page we get an Internal Server Error due to the timeout of 600 seconds. During the processing of that page there is no unusual load on the DB (MariaDB), but found out a php-fpm process consuming 100% of CPU. We "straced" the process and osberved a kind of loop consisting of a cache file read, followed by a SELECT from the mdl_context table.

```
access("/var/www/html/mod/choice/lib.php", F_OK) = 0
access("/var/www/html/mod/choice/lib.php", F_OK) = 0
access("/moodledata/cache/cachestore_file/default_application/core_coursemodinfo/432-cache/432-78dfb667b9e7212d729b7c511330f8d9.cache", F_OK) = 0
openat(AT_FDCWD, "/moodledata/cache/cachestore_file/default_application/core_coursemodinfo/432-cache/432-78dfb667b9e7212d729b7c511330f8d9.cache", O_RDONLY) = 7
fstat(7, {st_mode=S_IFREG|0666, st_size=109543, ...}) = 0
lseek(7, 0, SEEK_CUR)                   = 0
flock(7, LOCK_SH)                       = 0
read(7, "O:8:\"stdClass\":9:{s:7:\"modinfo\";"..., 8192) = 8192
read(7, "ectionid\";s:4:\"3713\";s:6:\"module"..., 8192) = 8192
read(7, ":7:\"section\";s:1:\"1\";s:9:\"sectio"..., 8192) = 8192
read(7, "lass\":11:{s:2:\"id\";s:3:\"143\";s:2"..., 8192) = 8192
read(7, "ded\";s:10:\"1446555327\";s:7:\"visi"..., 8192) = 8192
read(7, "le\";s:1:\"3\";s:5:\"added\";s:10:\"14"..., 8192) = 8192
read(7, "\";s:9:\"sectionid\";s:4:\"3713\";s:6"..., 8192) = 8192
read(7, "0\";s:19:\"visibleoncoursepage\";i:"..., 8192) = 8192
read(7, ":\"section\";s:1:\"1\";s:9:\"sectioni"..., 8192) = 8192
read(7, "19:\"visibleoncoursepage\";i:1;s:1"..., 8192) = 8192
read(7, "12:\"GIOVEDI' 3 settembre, 17:00-"..., 8192) = 8192
read(7, "\"0\";s:4:\"name\";s:83:\"VENERDI' 11"..., 8192) = 8192
read(7, ";s:10:\"visibleold\";s:1:\"0\";s:4:\""..., 8192) = 8192
read(7, " 69, 64);\"><span style=\"\"><span "..., 8192) = 3047
read(7, "", 8192)                       = 0
flock(7, LOCK_UN)                       = 0
close(7)                                = 0
sendto(5, "M\0\0\0\3SELECT * FROM mdl_context W"..., 81, MSG_DONTWAIT, NULL, 0) = 81
poll([{fd=5, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=5, revents=POLLIN}])
recvfrom(5, "\1\0\0\1\0066\0\0\2\3def\6moodle\vmdl_context"..., 25963, MSG_DONTWAIT, NULL, NULL) = 459
sendto(5, "\267\0\0\0\3SELECT ctx.path, ra.roleid,"..., 187, MSG_DONTWAIT, NULL, 0) = 187
poll([{fd=5, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=5, revents=POLLIN}])
recvfrom(5, "\1\0\0\1\0032\0\0\2\3def\6moodle\3ctx\vmdl_con"..., 25504, MSG_DONTWAIT, NULL, NULL) = 609
access("/var/www/html/mod/choice/lib.php", F_OK) = 0
access("/var/www/html/mod/choice/lib.php", F_OK) = 0
```

We also tried to wipe the cache, but the problem is still there.
Due to the long list of reservations it sounds like something related to the module, but we are not sure.

May you give us some hint on how to address the problem (maybe a workround to be applied in the settings) or a way to troubleshoot it more in depth? Please also consider this is on a production instance, so unfortunately we cannot take any action affecting the user experience.

Thank you
PL

**Comment by bobopinna** [comment]
Hi,
if this `access("/var/www/html/mod/choice/lib.php", F_OK) = 0` is right, it
seems that the problem is with Choice plugin.

Did you check it?

**Comment by plrunner** [comment]
Thanks for the prompt reply.

The /var/www/html/mod/choice/ folder and its content are recursively accessible by the user that php-fpm is running as.
Actually I didn't look into the "choice" plugin in the first instance, as I meant that syscall to just check that the file exists and the return code is successful. Anyway I just checked and everything seems ok with it.

What did sound strange to you about that syscall?

Thank you
PL

**Comment by plrunner** [comment]
I finally got what you meant: looks like that loop is due to the choice mod, right?
I think you got a point and it's worth investigating.

If something related to "reservations" comes up I will then reopen this issue.

Thank you
PL
