### ISSUE TITLE
Teacher list is empty

### ISSUE THREAD

**Issue by ingamr** [bobopinna/moodle-mod_reservation#32]
On settings of event, teachers selector is empty.

**More information:**
select with name="teachers[]" and id="id_teachers"

**Environment:** 
moodle 4.0.10 
php 7.4
plugin version 4.0.1

**Comment by bobopinna** [comment]
Hello,
teacher selector should show course teachers.
Did you added some teachers to your course?

**Comment by ingamr** [comment]
Hello,
Yes, we have teachers in our course.

**Comment by bobopinna** [comment]
Hello,
try to update to last commit ([e22ff7e](https://github.com/bobopinna/moodle-mod_reservation/commit/e22ff7e90e99ee7c6bd2d7e6f44cd5fffeb96e91)).

It could be a problem with user capabilities check.

HTH,
Roberto

**Comment by ingamr** [comment]
Hello,
We have updated the plugin with last version of master and it doesn't resolve this problem.
We have one teacher on this course.
![image](https://github.com/bobopinna/moodle-mod_reservation/assets/142578732/95bc39dc-a91f-4d97-b1f2-fd917b12b7cb)
![image](https://github.com/bobopinna/moodle-mod_reservation/assets/142578732/f6d3736d-3211-4e9d-a059-46f07388fd36)

**Comment by bobopinna** [comment]
Please check if the teacher has other roles (such as Manager or Student) in that course or in course categories where that course is.

You can check teacher permission under Course administration -> Users/Participants -> Permission -> Check permission
If your teacher has "reserve" capability there is something in her/his roles assignment that must be fixed.

HTH,
Roberto

**Comment by pgt74** [comment]
Hello Roberto,
Same issue here.
I did update to e22ff7e... still no teacher showing up in that box, although I do have 2 fully regular teachers declared in that course.
Thanks for any help !
KR,
Paul

**Comment by ingamr** [comment]
Hello
It doesn't work.
Do you have another solution ?

**Comment by bobopinna** [comment]
Hello,
I'm sorry but I can't reproduce your problem so I do not have another solution.
You can try to set Moodle debug at developer level and check your server error logs.
If get some errors about reservation plugin when you try to modify a reservation those errors could help me to understand what's happens.

Roberto
