### ISSUE TITLE
CSV Import template

### ISSUE THREAD

**Issue by LorenzoDesign** [bobopinna/moodle-mod_reservation#33]
Hi everyone,
first of all thanks for your dedication and compliments for the plugin.

One very interesting functionality is to import dates from a csv file.
I not was able to find any csv file to use as template to import.

Would be nice to provide this file. 
The file can be linked in the moodle plugin directory home page,
here in the description
or can be included in the zip file.

Thanks

**Comment by ian-4tek** [comment]
I am also interrested in a csv template. I'm currently mistified as to the requirements and how to use this. The documentation seems to be absent. Anyone use this and have a template they can provide?

I would be most gratefull. Thanks

**Comment by ian-4tek** [comment]
Digging in the code I'm guessing that the csv headers should look like the following:

`name,teachers,location,locationtext,timestart,timeend,timeopen,timeclose,note,maxrequest,showrequest,parent,overbook,requestlimit_1,field_1,operator_1,matchvalue_1,completionreserved
`
Is this correct, or am I lost?

Please help.

**Comment by bobopinna** [comment]
Hello,
sorry for the big delay in response.
Reservation upload works as Moodle user upload works.
There is an online help, the question mark near "Reservations upload" in the upload page.
 
For a full description of Reservation upload file format you could see new [documentation](https://github.com/bobopinna/moodle-mod_reservation/blob/master/UPLOAD.md).

**Comment by ALn668** [comment]
Hallo, i'm a complete newbie.

When i try to import this text file: 
```
course;section;name;timestart
provaGOU24;1;101ProvaProvaProva;2024-12-17 12:42:00
```
the answer is
Warning: Undefined array key 4 in /var/www/html/moodle/mod/reservation/tool/upload.php on line 325
...
Warning: Undefined array key 12 in /var/www/html/moodle/mod/reservation/tool/upload.php on line 325
10 times and
![image](https://github.com/bobopinna/moodle-mod_reservation/assets/154673138/64039f01-ea43-4f92-8401-9d0abbfe726c)

On row 12 is the correct result.
Thank you very much
