### ISSUE TITLE
AJAX requests and UTF-8

### ISSUE THREAD

**Issue by wiktorwandachowicz** [bobopinna/moodle-mod_reservation#6]
There is a sublimits setting in **mod_reservation**, which allows to select rules for each sublimit.
On the right side there is a field which has Javascript support and makes AJAX requests to `matchlist.php`

There are two issues:

1) Our installation has UTF-8 strings in database, and in Polish language we have 9 (18 with upper- and lowercase) characters that do not fit into Western Europe encoding. These characters are returned garbled in displayed popup div block.
My analysis proved that:
* Returned response lacks HTTP header with specification of UTF-8 encoding.
* Wrong PHP function "htmlentities()" was being used for transforming international characters, while it should be "htmlspecialchars()".

2) When there are too many responses from `matchlist.php`, they are not shown because CSS class "matchlist" lacks the style "overflow-y: auto;".

All these problems were resolved and can be found in my forked **moodle-mod_reservation** repository, namely commits:
https://github.com/wiktorwandachowicz/moodle-mod_reservation/commit/c6093bb0edcb36e6df85a12a3ddbf238906191e2
and
https://github.com/wiktorwandachowicz/moodle-mod_reservation/commit/bebcafb224fa0d1934cdd91c2d01f0ae41bf5f91

**Comment by wiktorwandachowicz** [comment]
To note, commits mentioned earlier are for [MOODLE_27_STABLE](https://github.com/bobopinna/moodle-mod_reservation/tree/MOODLE_27_STABLE) of yours and my [MOODLE_28_STABLE](https://github.com/wiktorwandachowicz/moodle-mod_reservation/tree/MOODLE_28_STABLE) branch.

Commits for [master](https://github.com/wiktorwandachowicz/moodle-mod_reservation/tree/master) branch are as follows:
https://github.com/wiktorwandachowicz/moodle-mod_reservation/commit/36dd8f6385d5584a8e176f36002df6ddfd74c59a
and
https://github.com/wiktorwandachowicz/moodle-mod_reservation/commit/acd3ce24201e0fbe7bc656f470f69b45684216d3

**Comment by scara** [comment]
Hi @wiktorwandachowicz,
you could fix it in the Moodle way by using `s()`: read more at https://docs.moodle.org/dev/Output_functions#p.28.29_and_s.28.29.

HTH,
Matteo

**Comment by wiktorwandachowicz** [comment]
Thanks @scara,
so you suggest to replace the following:
`addslashes(htmlspecialchars($value->$fieldname))`
with single:
`s($value->$fieldname)`

Is the second equal/better that the first?

I just tracked the problem down to `htmlentities()` which was giving incorrect output in this case.
I didn't want to interfere with the original code too much.

**Comment by wiktorwandachowicz** [comment]
Ok, I think I get it.
Most probably you were thinking about using `s()` two times like this, right?
```PHP
    echo '<a href="javascript:void(0)" onclick="document.getElementById(\''.$matchvalue.'\').value=\''
        .addslashes(s($value->$fieldname))
        .'\'; document.getElementById(\'matchvalue_list\').style.display=\'none\';">'
        .s($value->$fieldname).'</a><br />'."\n";
```

**Comment by scara** [comment]
Yes that should be the fix: Moodle has some functions and APIs that should be used and the issue here is what you've perfectly tracked down but the resolution should IMHO be _using the Moodle way_ since the original code was not following this best practice (and you could search for the same pattern in other places, if any).

Please test it on your dev instance and wait for the mantainer, @bobopinna, for his thoughts.

TIA,
Matteo

**Comment by wiktorwandachowicz** [comment]
Tested as requested with following **test.php**:

```PHP
<?php
//define ('CLI_SCRIPT', 1);
require_once('../../config.php');
require_once($CFG->libdir.'/weblib.php');

$val = "Łódź ' \"BP\"";
echo "<pre>" . PHP_EOL;
echo "Plain:" . PHP_EOL;
echo "unescaped:        " . $val . PHP_EOL;
echo "htmlentities:     " . htmlentities($val) . PHP_EOL;
echo "htmlspecialchars: " . htmlspecialchars($val) . PHP_EOL;
echo "Moodle s(val):    " . s($val) . PHP_EOL;

echo PHP_EOL;

echo "Added slashes:" . PHP_EOL;
echo "unescaped:        " . addslashes($val) . PHP_EOL;
echo "htmlentities:     " . addslashes(htmlentities($val)) . PHP_EOL;
echo "htmlspecialchars: " . addslashes(htmlspecialchars($val)) . PHP_EOL;
echo "Moodle s(val):    " . addslashes(s($val)) . PHP_EOL;

echo "</pre>";
```
It produces following HTML:

```HTML
<pre>
Plain:
unescaped:        Łódź ' "BP"
htmlentities:     Ł&oacute;dź ' &quot;BP&quot;
htmlspecialchars: Łódź ' &quot;BP&quot;
Moodle s(val):    Łódź &#039; &quot;BP&quot;

Added slashes:
unescaped:        Łódź \' \"BP\"
htmlentities:     Ł&oacute;dź \' &quot;BP&quot;
htmlspecialchars: Łódź \' &quot;BP&quot;
Moodle s(val):    Łódź &#039; &quot;BP&quot;
</pre>
```
Only my original, third variant gives correct result: `addslashes(htmlspecialchars($value->$fieldname))`

Produced HTML fragment is used in Javascript to find DOM element by name, as in:
```javascript
<a href="javascript:void(0)" onclick="document.getElementById('id_matchvalue_1').value='Łódź \' &quot;BP&quot;'; document.getElementById('matchvalue_list').style.display='none';" id="yui_3_17_2_3_1479814555320_1371">Łódź ' "BP"</a>
```

**Comment by scara** [comment]
Hi @wiktorwandachowicz,
are you sure that you need to escape single quotes only via slash and that using HTML entities for them (`&#039`) doesn't work at all?

TIA,
Matteo

**Comment by wiktorwandachowicz** [comment]
Hi @scara,

* [BAD] `addslashes(s($value->$fieldname))` - no go, produces incorrect Javascript:
    `document.getElementById('id_matchvalue_1').value='Łódź ' "BP"';`
* [BAD] just `s($value->$fieldname)` - also wrong, produces the same Javascript:
    `document.getElementById('id_matchvalue_1').value='Łódź ' "BP"';`
* [OK] proposed `addslashes(htmlspecialchars($value->$fieldname))` - works as it should:
    `document.getElementById('id_matchvalue_1').value='Łódź \' "BP"';`

Clicking on element with incorrect Javascript does not modify input field in the browser.

Please note that proposed fix applies to Javascript part (see: `.value=` in snippet below)
and _not_ to HTML that is inside `<a>` tag:
```HTML
<a href="javascript:void(0)" onclick="document.getElementById('id_matchvalue_1').value='Łódź \' &quot;BP&quot;'; document.getElementById('matchvalue_list').style.display='none';" id="yui_3_17_2_3_1479819896525_1373">
Łódź ' "BP"
</a>
```
For HTML output the `s()` function is perfectly fine.

BTW. Thanks a lot for pointing out the `s()` and `p()` functions.
I'm going to use them from now on where applicable.

**Comment by scara** [comment]
OK 👍.
If you want to go further with that route, please, have a read about https://github.com/moodle/moodle/blob/f31e1e8b258eb89ae43a73d0a9bda41e49581edd/lib/weblib.php#L118 too i.e. you should use  `addslashes_js()` instead of `addslashes()`.

If you want to deepen those functions, please, start reading at https://docs.moodle.org/dev/Security#Clean_and_escape_data_before_output (and then at the whole page) and https://docs.moodle.org/dev/Security:Cross-site_scripting.

HTH,
Matteo

**Comment by wiktorwandachowicz** [comment]
After some thought and experimenting, I ended up with following:
```PHP
if (!empty($value->$fieldname)) {
    echo '<a href="javascript:void(0)" onclick="document.getElementById(\''.$matchvalue.'\').value=\''
        .addslashes_js(htmlspecialchars($value->$fieldname))
        .'\'; document.getElementById(\'matchvalue_list\').style.display=\'none\';">'
        .s($value->$fieldname).'</a><br />'."\n";
}
```
Commits in my cloned repository can be found at:
* https://github.com/wiktorwandachowicz/moodle-mod_reservation/commit/5b706b3412867c28640692cbdcf5d0a00b1ce3a3 - for [MOODLE_28_STABLE](https://github.com/wiktorwandachowicz/moodle-mod_reservation/tree/MOODLE_28_STABLE)
* https://github.com/wiktorwandachowicz/moodle-mod_reservation/commit/318eaafa099231589dd506b8f889505990ebdeb8 - for [master](https://github.com/wiktorwandachowicz/moodle-mod_reservation/tree/master)

**Comment by bobopinna** [comment]
Hi,
tested and merged to master.

S function add unwanted entities for single quote.

Thanks a lot.
Roberto.
