### ISSUE TITLE
Parse error in locallib.php on line 616

### ISSUE THREAD

**Issue by xescar** [bobopinna/moodle-mod_reservation#8]
The following error is shown working with PHP 5.4.0.
Parse error: syntax error, unexpected '=', expecting ')' in /usr/moodle/mod/reservation/locallib.php on line 616

Code works fine with PHP 7.0

The issue is in the following line:
            if (!empty($events = calendar_get_events_by_id(array($request->eventid)))) {

A Workaround is moving the assignment before the "if":
            $events = calendar_get_events_by_id(array($request->eventid));
            if (!empty($events)) {

**Comment by bobopinna** [comment]
Fixed on MOODLE_32_STABLE and master branches.

Cheers.
