### ISSUE TITLE
A space between

### ISSUE THREAD

**Issue by dinism** [bobopinna/moodle-mod_reservation#9]
Is it possible?
A space after **:** in all sentences
![imagem](https://user-images.githubusercontent.com/14828021/34950398-f7e94270-fa0a-11e7-9439-acfd1f5a0e6f.png)
 👍 
And here? A double space?
![imagem](https://user-images.githubusercontent.com/14828021/34950619-92f0ec50-fa0b-11e7-9afa-1506116fb213.png)

**Comment by bobopinna** [comment]
Fixed by last commit
